# Generated by Django 2.1.1 on 2018-09-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ('-date_effective',), 'verbose_name': 'Расписнаие', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterModelOptions(
            name='scheduleentry',
            options={'ordering': ('title',), 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='scheduleentrysection',
            options={'ordering': ('title',), 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
